name: Deploy Repository to ADO

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout current GitHub repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # fetch-depth: fetches full history of repo; avoids creation of shallow clone
          fetch-depth: 0
      
      # Auth to Azure DevOps
      - name: Set up .netrc for Azure DevOps authentication
        run: |
          echo "machine dev.azure.com login ${{ secrets.AZURE_DEVOPS_PAT }} password ${{ secrets.AZURE_DEVOPS_PAT }}" > ~/.netrc
          chmod 600 ~/.netrc
  
      - name: Add Azure DevOps remote
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          git remote add azure https://dev.azure.com/bqtruong/_git/azure-rapid-candle
      
      # Step to check if repository is shallow; issue occurs when pushing to Azure Repos
      - name: Check if the repository is shallow
        id: check_shallow
        run: echo "shallow=$(git rev-parse --is-shallow-repository)" >> $GITHUB_ENV
    
      - name: Unshallow the repository if needed
        if: env.shallow == 'true'
        run: |
          git fetch --unshallow azure
  
      - name: Fetch from Azure Repos with full history
        if: env.shallow == 'false'
        run: |
          git fetch azure

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Merge changes from this GitHub repos to Azure Repos; auto-selects AR if conflict arises
      - name: Merge changes from Azure Repos
        run: |
          git merge -X theirs azure/main --allow-unrelated-histories

      - name: Push to Azure Repos
        run: |
          git push azure HEAD:main